name: Deploy
on:
  pull_request:
    branches:
      - 'staging'
    types:
      - closed
  push:
    branches:
      - 'staging'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BASE_PATH: dring-ring-react

    name: Build And Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          scp_source: ./build/*
          scp_target: ./websites/staging/drinkring.webkor.pl